### ISSUE TITLE
"Choose resized" doesn't work in manual test

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ckfinder#12]
![image](https://user-images.githubusercontent.com/156149/48563202-13674780-e8f4-11e8-8ad8-df516cefadec.png)

**Comment by Reinmar** [comment]
Not sure if this is on our side or the CKF instance that we does not allow it. But we'll be using it in the docs so it'd be good to enable resizing on the server (if that's a problem here).

**Comment by jodator** [comment]
Might be something with CORS - https://github.com/ckeditor/ckeditor5-ckfinder/issues/14#issuecomment-439085536.
