### ISSUE TITLE
CKFinder is displayed below the manual test description

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ckfinder#13]
![image](https://user-images.githubusercontent.com/156149/48563349-67722c00-e8f4-11e8-90ac-2cd578d2849a.png)

**Comment by jodator** [comment]
So the CKFinder's modal window uses `z-index: 8999` (hardcoded) while manual tests uses `9999`.

AFAIR there where no reports of that z-index setting on CKFinder part.

To "fix" this in manual tests we could add to the `ckfinder.html` manual test:
```html
<style>
	#ckf-modal {
		z-index: 10000 !important;
	}
</style>
```

**Comment by jodator** [comment]
ps.: This cannot be quickly fixed - it is hardcoded in CKFinder code. I've reported the [z-index for CKFinder modal issue](https://github.com/ckfinder/ckfinder/issues/373).

**Comment by Reinmar** [comment]
> To "fix" this in manual tests we could add to the `ckfinder.html` manual test:

👍
