### ISSUE TITLE
Uploading a PDF in a manual test ended up with an error

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ckfinder#14]
![image](https://user-images.githubusercontent.com/156149/48563605-fc752500-e8f4-11e8-91b1-256c352b44e8.png)
![image](https://user-images.githubusercontent.com/156149/48563615-00a14280-e8f5-11e8-9a2f-f13e62554b98.png)

The same as in #12 – we'll be using this in the docs, so it'd be good if it worked.

**Comment by Reinmar** [comment]
Creating a new folder:

![image](https://user-images.githubusercontent.com/156149/48563709-334b3b00-e8f5-11e8-81cd-bd20e311edba.png)

So, apparently, there are no write rights there.

**Comment by jodator** [comment]
> So, apparently, there are no write rights there.

It looks like something wrong with the CORS... I might be wrong here but this instance is working on the docs: https://ckeditor.com/docs/ckfinder/demo/ckfinder3/samples/modals.html.

**Comment by jodator** [comment]
I'd say that:

1. This comes probably due to server configuration - it works on the same domain.
1. It is a dup of #12 because of previous point.
