### ISSUE TITLE
CKFinder toolbar icon

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-ckfinder#2]
The CKFinder can host Images as well as other files.

For images we will insert them as `<img>` tags while the other might be inserted as links to a file.

Thinks to consider is:
- do we should allow such behavior? (might be configurable through CKFinder options)
- how the icon should look like then.

/cc @Reinmar @oleq

**Comment by RyszardB** [comment]
v1:
![v1](https://user-images.githubusercontent.com/17498197/48304285-813bf980-e517-11e8-8353-fec7ab94d9b4.png)

v2:
![v2](https://user-images.githubusercontent.com/17498197/48304286-813bf980-e517-11e8-9ce4-22bbb737a28c.png)

v3:
![v3](https://user-images.githubusercontent.com/17498197/48304287-81d49000-e517-11e8-95be-c9f2a2af232d.png)

v4:
![v4](https://user-images.githubusercontent.com/17498197/48304288-826d2680-e517-11e8-9349-9341aaa8e6d1.png)

**Comment by jodator** [comment]
From the above I like the **v4**. Mostly because of the `+` badge.

**Comment by AnnaTomanek** [comment]
Also v4, also for the "+" part, but none of them is 100% convincing/understandable to me. I know it's a difficult task though :/

The folder icon is confusing, looks like some sort of browser/open files/open folder/open project.

@RyszardB any other ideas around the "+"? Can we steal some inspiration from other products?

**Comment by Reinmar** [comment]
Crazy idea (not sure if doable) – can we show that there's an image in that folder? 

It came to my mind because we're considering titling this button "Insert image or file".

**Comment by RyszardB** [comment]
v5
![v5](https://user-images.githubusercontent.com/17498197/48491621-43e1af80-e828-11e8-8625-392467c314c5.png)

v6
![v6](https://user-images.githubusercontent.com/17498197/48491630-4cd28100-e828-11e8-9b64-b60259a89d63.png)

**Comment by dkonopka** [comment]
First of all, I want to see this icon next to others instead aligned to the right because I'm worried it will be looking a little bit different. 

Anyway, as everyone said, I'm +1 with version number 4 👍 We could try to add inside an image, but we shouldn't overuse details (remember about Low DPI).

**Comment by RyszardB** [comment]
![artboard 2x](https://user-images.githubusercontent.com/17498197/48491773-9753fd80-e828-11e8-8936-202164a8ba0c.png)

**Comment by RyszardB** [comment]
![v6-2](https://user-images.githubusercontent.com/17498197/48492051-37aa2200-e829-11e8-8736-b04dea752b6e.png)

![v5-2](https://user-images.githubusercontent.com/17498197/48492052-37aa2200-e829-11e8-8cf8-d02b372700c0.png)

![v4-2](https://user-images.githubusercontent.com/17498197/48492053-3842b880-e829-11e8-9114-b1561e908140.png)

**Comment by RyszardB** [comment]
![v6-3](https://user-images.githubusercontent.com/17498197/48493108-8b1d6f80-e82b-11e8-9bb0-7efc27235404.png)

![v5-3](https://user-images.githubusercontent.com/17498197/48493110-8b1d6f80-e82b-11e8-9112-a8cfffed28d6.png)

![v4-3](https://user-images.githubusercontent.com/17498197/48493111-8b1d6f80-e82b-11e8-9515-44a59197c444.png)

**Comment by oleq** [comment]
I created a couple of mockups too. They're more in line with the current icon convention:

v7
![v3](https://user-images.githubusercontent.com/1099479/48552341-9f6b7600-e8d8-11e8-9184-33712c6980e1.png)

v7b
![v3b](https://user-images.githubusercontent.com/1099479/48552342-9f6b7600-e8d8-11e8-850e-55185d700fea.png)

v8
![v2](https://user-images.githubusercontent.com/1099479/48552339-9ed2df80-e8d8-11e8-933c-e99e2fc536ef.png)

v8b
![v2b](https://user-images.githubusercontent.com/1099479/48552340-9ed2df80-e8d8-11e8-863f-bba49013e4b2.png)

**Comment by dkonopka** [comment]
I would choose @oleq's v8 because "+" sign on the white background is hard to notice (mockup vs live demo makes difference). 

Anyways I agree: light bg of plus sign is looking good on this mockups because Rysiek enlarged this icon (it's around 20px height I guess where we are trying to make icons ~17-18px).

**Comment by RyszardB** [comment]
18x18px
<img width="293" alt="screenshot 2018-11-15 at 15 48 29" src="https://user-images.githubusercontent.com/17498197/48560447-19f2c080-e8ee-11e8-964e-d7806cb107c5.png">

![artboard](https://user-images.githubusercontent.com/17498197/48560509-40186080-e8ee-11e8-94ff-e4e5d5da71e5.png)

**Comment by oleq** [comment]
> I think I like Rysiek's proposal the most:

I also like it but when downscaled, its details are lost. It's hard to tell what the bulge on the top is about.

**Comment by oleq** [comment]
Another round of designs with more variations and improvements. My personal favorites are 2.3 and 2.5.

----

### 1.1
<img src="https://user-images.githubusercontent.com/1099479/48629774-d914ad80-e9ba-11e8-9e8d-e73d9cfb86ce.png" width="640" />

### 1.2
<img src="https://user-images.githubusercontent.com/1099479/48629776-d914ad80-e9ba-11e8-9433-6d40104c4914.png" width="640" />

### 1.3
<img src="https://user-images.githubusercontent.com/1099479/48629778-d9ad4400-e9ba-11e8-9a5f-ecb47d8e5a44.png" width="640" />

### 1.4
<img src="https://user-images.githubusercontent.com/1099479/48629779-d9ad4400-e9ba-11e8-930a-a1e6ef840d76.png" width="640" />

### 2.1
<img src="https://user-images.githubusercontent.com/1099479/48629780-d9ad4400-e9ba-11e8-96a0-2d85b1aae95e.png" width="640" />

### 2.2
<img src="https://user-images.githubusercontent.com/1099479/48629781-da45da80-e9ba-11e8-8459-0d2fb2f01532.png" width="640" />

### 2.3
<img src="https://user-images.githubusercontent.com/1099479/48629782-da45da80-e9ba-11e8-9096-5f7c261fefb5.png" width="640" />

### 2.4
<img src="https://user-images.githubusercontent.com/1099479/48629784-da45da80-e9ba-11e8-9552-20977b2e1759.png" width="640" />

### 2.5
<img src="https://user-images.githubusercontent.com/1099479/48629785-da45da80-e9ba-11e8-804c-98d311937dc7.png" width="640" />

### 3.1
<img src="https://user-images.githubusercontent.com/1099479/48629786-dade7100-e9ba-11e8-81a4-c8126308a885.png" width="640" />

### 3.2
<img src="https://user-images.githubusercontent.com/1099479/48629788-dade7100-e9ba-11e8-9415-5ed131087d78.png" width="640" />

### 3.3
<img src="https://user-images.githubusercontent.com/1099479/48629789-dade7100-e9ba-11e8-85c2-efc0d6c0923a.png" width="640" />

### 3.4
<img src="https://user-images.githubusercontent.com/1099479/48629790-dade7100-e9ba-11e8-96fb-af111238f373.png" width="640" />

**Comment by dkonopka** [comment]
3.1 - 3.4 icons looks like "Create a gallery button" so for me it's not a proper way to go.

As I said earlier, black "+" symbol is better (LoDPI issues), so I'm voting for proposal: *2.4.

OTOH I'm ok with 2.3 & 2.5. Mixing a folder, an image & a plus sign is almost impossible, so the only solution is to stay with folder I guess.

**Comment by jodator** [comment]
2.5 :+1:

**Comment by oleq** [comment]
After "F2F" talks we went with the following design:

<img width="505" alt="screenshot 2018-11-19 at 11 58 55" src="https://user-images.githubusercontent.com/1099479/48703042-ddc3a680-ebf2-11e8-8e24-3d1438324207.png">
