### ISSUE TITLE
CKFinder won't open if closed and re–opened

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ckfinder#23]
1. Open the guide in features/ckfinder.html.
2. Open the CKF in "Demo" (features/ckfinder.html#demo)
3. Close it.
4. Click the button again.

**Expected**: CKF should show up.

**Actual**: Nothing shows up.

**Comment by jodator** [comment]
Wrong usage of `editor.config`: https://github.com/ckeditor/ckeditor5-utils/issues/257. Fix is on the way.
