### ISSUE TITLE
Use the new version of CKFinder (3.4.5) in docs

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ckfinder#26]
ATM 

![image](https://user-images.githubusercontent.com/1099479/49145115-574c4a80-f2ff-11e8-9b8e-bd4819757251.png)

New version:

![image](https://user-images.githubusercontent.com/1099479/49145132-66cb9380-f2ff-11e8-94f3-a7499bbd6a76.png)

Related to https://github.com/ckeditor/ckeditor5-ckfinder/issues/18.

**Comment by Reinmar** [comment]
Really... 🏇 ? :D

**Comment by jodator** [comment]
I've pinged @zaak about this. Should be up & running shortly.

**Comment by zaak** [comment]
Done, updated to new version.

**Comment by oleq** [comment]
I ran the docs and this is what I see now

![image](https://user-images.githubusercontent.com/1099479/49150355-dd22c280-f30c-11e8-9e70-2c812988003d.png)

@jodator @zaak: can you check this out?

**Comment by jodator** [comment]
fix on tha way

**Comment by jodator** [comment]
OK it is fixed by @zaak. Thanks :tada:.

Upcoming releases should work after updating without such problems.
