### ISSUE TITLE
Cannot read property 'modal' of undefined (again)

### ISSUE THREAD

**Issue by gkzsolt** [ckeditor/ckeditor5-ckfinder#50]
Hi,
I am using a CKEditor build and trying to use - or add? - the CKFinder integration to it. I am struggling now for half a day but to no avail.
The editor builds - I am using InlineEditor, btw. - _do include_ the CKFinder plugin, as I see, it is listed in InlineEditor.builtinPlugins, and according to the docs it is also enabled: "This feature is enabled by default in all builds." So I don't have to add CKFinder to my plugin list.
In my app I instantiate an editor and try to access the CKFinder with its ui toolbar button:

`const CKEditor = require('@ckeditor/ckeditor5-build-inline');`
`  CKEditor
        .create( document.querySelector('#editor'), {`
`toolbar: [ 'ckfinder' ],`
`ckfinder: {
                uploadUrl: '...',
            }`
`})
        .then(...)`

I then build a bundle with webpack. But when I click the ckfinder button I got the infamous 

> Cannot read property 'modal' of undefined

All my internet searches revealed only the question "Have you added ckfinder.js to a webpage? 
Check the CKFinder for CKEditor5 integration feature guide."

Well, I checked the CKFinder for CKEditor5 integration feature guide. 

> The easiest way to load the CKFinder library is to include the <script> tag loading the ckfinder.js file first:

Yes, but I am not going to do this, because I am building a bundle with webpack - like the whole CKEditor docs suggest - and with webpack you don't load JS using script tags. Is CKFinder loaded by the InlineEditor build? I see it in the devDependencies, but don't know how to check it better (the code is minimised.)
If I add:
`import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';`
as the example in the integration guide, I get a _ckeditor-duplicated-modules_ error, which also seems to confirm that ckfinder is loaded. So where is the problem, what am I doing wrong?

Thank you for any help.

**Comment by Mgsy** [comment]
Hi, you're right that CKFinder is enabled in all builds by default, please see - https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js#L15. It means that there's no need to import it again. 

As you noticed, this error occurs if you don't add a `ckfinder.js` via `<script>` tag to your application. CKFinder plugin is just a "bridge" between CKEditor 5 and CKFinder, so it's required to attach CKFinder to make it work. Just add it to your HTML page and it should be fine.

**Comment by gkzsolt** [comment]
Thanks, attaching through a `script` tag seems to work right now, although it is not quite standard for a webpack build.I hope you are working on a better integration in the future.
